name: Build with Gradle

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x SequencerMod/gradlew
      
    - name: Build with Gradle
      run: cd SequencerMod && ./gradlew build --no-daemon
      
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          SequencerMod/build/libs/*.jar
        retention-days: 7
        
    - name: Upload test reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          SequencerMod/build/reports/
        retention-days: 7
